CREATE DATABASE mailinglist;

CREATE TABLE `user` ( 
	`id` INT(11) NOT NULL AUTO_INCREMENT , 
	`name` VARCHAR(35) NOT NULL , 
	`email` VARCHAR(75) NOT NULL , 
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	PRIMARY KEY (`id`)
) 
ENGINE = InnoDB;